services:
  pwnenv:
    container_name: pwnenv
    hostname: pwnenv
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        GROUPNAME: $GROUPNAME
    user: $UID:$GID
    tty: true
    volumes:
      - type: bind
        source: ./workdir
        target: /home/$USERNAME/workdir
